# Generated by Django 4.1.2 on 2022-10-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_remove_file_remark_file_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=30),
        ),
    ]
